### ISSUE TITLE
Error when selecting "Prototype token" context menu option on v10

### ISSUE THREAD

**Issue by Gawdl3y** [kandashi/sidebar-context#8]
The following error is being produced when clicking "Prototype token" on v10:
```
foundry.js:711 TypeError: Cannot read properties of undefined (reading 'find')
[No packages detected]
    at TokenConfig.getData (foundry.js:69902:49)
    at async TokenConfig._render (foundry.js:4959:18)
    at async TokenConfig._render (foundry.js:5684:5)
```

Even though the error doesn't include the module in its stack trace, the vanilla button on the character sheet to open the prototype token is still working, so I assume the method to open it has changed slightly.

**Comment by Weissrolf** [comment]
Same here, but fortunately the "Update child token" function still works. :-)

**Comment by Doresain** [comment]
Fixed in PR #9 - this is how I patched it for myself, at least.

**Comment by Weissrolf** [comment]
> Fixed in PR #9 - this is how I patched it for myself, at least.

How can PR versions be installed in Foundry?
